# Costumized forms for users (accounts/*.html)

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

# Customized forms that is generated by HttpResponse paramter under render()
# Class Meta:
#   fields -> Generates the fields required in order

class UserRegisterForm(UserCreationForm):
    #New email field for the form
                            #fields is set as not required
    email = forms.EmailField()
    email.required = False
    
    #Edit fields of forms (Override default class)
    class Meta:
        #Table receiving the fields data
        model = User
        #Fields name to be output and sent respectively
        fields = ['username', 'email', 'password1', 'password2']

#Update User information
class UserUpdateForm(forms.ModelForm):
    #Add field 
    email = forms.EmailField()
    email.required = False

    class Meta:
        model = User
        fields = ['username', 'email']

#Update Profile Information
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']